#!/usr/bin/env python3
from __future__ import annotations

import re
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
AC_DOC = ROOT / "ACCEPTANCE_CRITERIA.md"
PRESENCE_FILE = ROOT / "crates" / "acceptance" / "tests" / "acceptance_criteria_generated.rs"
RUNTIME_FILE = ROOT / "crates" / "acceptance" / "tests" / "ac_runtime_stubs_generated.rs"
OUT = ROOT / "crates" / "acceptance" / "AC_STATUS.md"

AC_RE = re.compile(r"AC-[A-Z]+-\d{3}")


def extract_ids(path: Path) -> set[str]:
    if not path.exists():
        return set()
    return set(AC_RE.findall(path.read_text()))


def iter_executable_sources() -> list[Path]:
    files: list[Path] = []
    for p in (ROOT / "crates").rglob("*.rs"):
        rel = p.relative_to(ROOT).as_posix()
        if rel.startswith("crates/acceptance/tests/"):
            continue
        files.append(p)
    return files


def extract_executable_ids() -> set[str]:
    ids: set[str] = set()
    for path in iter_executable_sources():
        ids.update(AC_RE.findall(path.read_text()))
    return ids


def domain_of(ac_id: str) -> str:
    return ac_id.split("-")[1]


def main() -> None:
    doc_ids = sorted(extract_ids(AC_DOC))
    if not doc_ids:
        raise SystemExit("No AC IDs in ACCEPTANCE_CRITERIA.md")

    presence_ids = extract_ids(PRESENCE_FILE)
    runtime_ids = extract_ids(RUNTIME_FILE)
    executable_ids = extract_executable_ids()

    rows: list[tuple[str, str, str]] = []
    summary = Counter()
    summary_by_domain: dict[str, Counter] = defaultdict(Counter)

    for ac_id in doc_ids:
        if ac_id in executable_ids:
            status = "DONE_EXECUTABLE"
            note = "Covered by executable test assertions"
        elif ac_id in presence_ids and ac_id in runtime_ids:
            status = "DONE_STUB_ONLY"
            note = "Acceptance presence + runtime stub generated"
        elif ac_id in presence_ids:
            status = "PARTIAL_PRESENCE_ONLY"
            note = "Presence test only"
        elif ac_id in runtime_ids:
            status = "PARTIAL_STUB_ONLY"
            note = "Runtime stub only"
        else:
            status = "MISSING"
            note = "No generated acceptance artifact"

        rows.append((ac_id, status, note))
        summary[status] += 1
        summary_by_domain[domain_of(ac_id)][status] += 1

    lines: list[str] = []
    lines.append("# Acceptance Criteria Status")
    lines.append("")
    lines.append("Generated by `scripts/generate_acceptance_status_report.py`.")
    lines.append("")
    lines.append("## Overall")
    lines.append("")
    lines.append(f"- Total AC IDs: **{len(doc_ids)}**")
    lines.append(f"- DONE_EXECUTABLE: **{summary['DONE_EXECUTABLE']}**")
    lines.append(f"- DONE_STUB_ONLY: **{summary['DONE_STUB_ONLY']}**")
    lines.append(f"- PARTIAL_PRESENCE_ONLY: **{summary['PARTIAL_PRESENCE_ONLY']}**")
    lines.append(f"- PARTIAL_STUB_ONLY: **{summary['PARTIAL_STUB_ONLY']}**")
    lines.append(f"- MISSING: **{summary['MISSING']}**")
    lines.append("")
    lines.append("## By Domain")
    lines.append("")
    lines.append("| Domain | DONE_EXECUTABLE | DONE_STUB_ONLY | PARTIAL | MISSING |")
    lines.append("| --- | ---: | ---: | ---: | ---: |")
    for domain in sorted(summary_by_domain):
        c = summary_by_domain[domain]
        partial = c["PARTIAL_PRESENCE_ONLY"] + c["PARTIAL_STUB_ONLY"]
        lines.append(
            f"| {domain} | {c['DONE_EXECUTABLE']} | {c['DONE_STUB_ONLY']} | {partial} | {c['MISSING']} |"
        )

    lines.append("")
    lines.append("## Per-AC Status")
    lines.append("")
    lines.append("| AC ID | Status | Notes |")
    lines.append("| --- | --- | --- |")
    for ac_id, status, note in rows:
        lines.append(f"| {ac_id} | {status} | {note} |")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n")

    print(f"wrote {OUT}")
    print(
        f"totals: executable={summary['DONE_EXECUTABLE']} stub_only={summary['DONE_STUB_ONLY']} "
        f"partial={summary['PARTIAL_PRESENCE_ONLY'] + summary['PARTIAL_STUB_ONLY']} missing={summary['MISSING']}"
    )


if __name__ == "__main__":
    main()
